import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import OauthWrapper from "./components/OauthWrapper";
import Header from "./Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RoboticsClub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative `}
      >
        <OauthWrapper>
        <Header/>
        {children}
        </OauthWrapper>
      </body>
    </html>
  );
}
